# fly.toml app configuration file generated for burguer-eccomerce on 2023-05-28T00:04:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "burguer-eccomerce"
primary_region = "bog"

[http_service]
  internal_port = 9091
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
